export const WORD_MAP: Map<string, Array<string>> = new Map([
    ['agar', ['SR388']],
    ['ai', ['one']],
    ['aikon', ['first']],
    ['aimar', ['once']],
    ['akala', ['spare']],
    ['akalai', ['spared']],
    ['ana', ['I', 'me']],
    ['anamahar', ['my']],
    ['aran', ['Aran']],
    ['aranda', ['because']],
    ['arocum', ['teleport']],
    ['aros', ['then']],
    ['aruar', ['offer']],
    ['aruari', ['offered']],
    ['ashka', ['if']],
    ['ashkar', ['raven']],
    ['ata', ['you']],
    ['atamahar', ['your']],
    ['atamis', ['yourself']],
    ['bados', ['lain']],
    ['bahi', ['truly']],
    ['bala', ['count']],
    ['balai', ['counted']],
    ['balan', ['bring']],
    ['balani', ['brought']],
    ['balis', ['prowess']],
    ['balta', ['back']],
    ['balu', ['want']],
    ['bama', ['already']],
    ['ban', ['foolish']],
    ['banta', ['intention']],
    ['barala', ['clone']],
    ['barash', ['worship', 'worships']],
    ['bari', ['infected']],
    ['baris', ['serve']],
    ['bash', ['ready']],
    ['behek', ['beak']],
    ['bema', ['leave']],
    ['bi', ['a', 'an']],
    ['bim', ['as']],
    ['borada', ['simple']],
    ['borodo', ['extinct']],
    ['bunta', ['great']],
    ['bura', ['this', 'these',]],
    ['chado', ['loading']],
    ['chanim', ['before']],
    ['chek', ['let']],
    ['chozo', ['chozo']],
    ['chuba', ['highly']],
    ['chuka', ['lie', 'lies']],
    ['daboris', ['proceed']],
    ['danam', ['symbolic']],
    ['dara', ['more']],
    ['darha', ['daughter']],
    ['dim', ['DNA']],
    ['dora', ['should']],
    ['dosh', ['to']],
    ['doshek', ['hand']],
    ['dun', ['three']],
    ['duruta', ['gathering']],
    ['ebores', ['somehow']],
    ['edda', ['here']],
    ['eddis', ['X']],
    ['eidis', ['enough']],
    ['eka', ['rule']],
    ['elar', ['rest']],
    ['elegar', ['prevent']],
    ['elemeh', ['narrowly']],
    ['emmi', ['EMMI']],
    ['es', ['now']],
    ['esen', ['than']],
    ['eshdor', ['must']],
    ['ess', ['now']],
    ['farag', ['attack']],
    ['faragi', ['attacked']],
    ['fasma', ['weak']],
    ['fehe', ['listen']],
    ['ferun', ['altar']],
    ['gabara', ['possess', 'possesses']],
    ['gabori', ['plotted']],
    ['gal', ['for']],
    ['galei', ['extreme']],
    ['galkisakra', ['bioweapon']],
    ['garama', ['actually']],
    ['garma', ['caution']],
    ['gelsu', ['soldiers']],
    ['geren', ['continue']],
    ['gimel', ['galaxy']],
    ['gorgan', ['preparation', 'preparations']],
    ['goro', ['put']],
    ['habar', ['has', 'have']],
    ['habari', ['had']],
    ['hadalu', ['destroying']],
    ['hadar', ['power', 'powers']],
    ['hadaris', ['powerful']],
    ['hadoran', ['well']],
    ['hakame', ['turn']],
    ['hakamei', ['turned']],
    ['hama', ['way', 'ways']],
    ['harek', ['yet']],
    ['haruna', ['live']],
    ['hasana', ['tribe', 'tribes']],
    ['hasari', ['took']],
    ['hass', ['yes']],
    ['hem', ['and']],
    ['henki', ['quiet']],
    ['hol', ['ever']],
    ['horek', ['accomplish']],
    ['hum', ['them', 'they']],
    ['humas', ['being']],
    ['hummahar', ['their']],
    ['hundar', ['become']],
    ['iamamar', ['follow']],
    ['idisi', ['managed']],
    ['ili', ['the']],
    ['ioris', ['plan', 'plans']],
    ['isbi', ['body']],
    ['ish', ['but']],
    ['ishka', ['from']],
    ['kadora', ['would']],
    ['karodan', ['contain']],
    ['kataru', ['defeat']],
    ['kedar', ['eyes']],
    ['ker', ['five']],
    ['kesa', ['encounter', 'encounters']],
    ['kinu', ['do']],
    ['kinui', ['done', 'did']],
    ['kisad', ['unlock']],
    ['kisadi', ['unlocked']],
    ['kohana', ['hold']],
    ['kran', ['can']],
    ['krani', ['could']],
    ['kuman', ['command', 'commands']],
    ['kumani', ['commanded']],
    ['kuni', ['which']],
    ['ladarha', ['daughter', 'daughters']],
    ['lamai', ['forced']],
    ['lavin', ['place', 'places']],
    ['lebat', ['physical']],
    ['les', ['in']],
    ['leshak', ['into']],
    ['lin', ['by']],
    ['loradabor', ['overestimate']],
    ['los', ['was']],
    ['maboris', ['called', 'told']],
    ['malabun', ['army', 'armies']],
    ['man', ['am']],
    ['manu', ['who']],
    ['mar', ['are']],
    ['maradan', ['ruin', 'ruins']],
    ['maradis', ['robe']],
    ['maril', ['will']],
    ['marona', ['until']],
    ['mawkin', ['Mawkin']],
    ['megor', ['descend']],
    ['megori', ['descended']],
    ['mehen', ['imagine', 'believe']],
    ['meheni', ['thought', 'thoughts']],
    ['mehirin', ['needed']],
    ['mei', ['on']],
    ['menke', ['honor']],
    ['meshta', ['performance']],
    ['metroid', ['Metroid', 'Metroids']],
    ['mir', ['that']],
    ['minobis', ['why']],
    ['mok', ['be']],
    ['mugi', ['were', 'was', 'been']],
    ['mul', ['consider']],
    ['mura', ['only']],
    ['mush', ['next']],
    ['nabor', ['instruction', 'instructions']],
    ['nabular', ['dread']],
    ['nakoren', ['alone']],
    ['nalon', ['return']],
    ['naloni', ['returned']],
    ['namayanis', ['necessary']],
    ['nebak', ['difficulty', 'difficulties']],
    ['neborien', ['superior']],
    ['nek', ['at']],
    ['nibur', ['intelligence']],
    ['nido', ['disguise', 'disguises']],
    ['nigu', ['know']],
    ['nim', ['this', 'it']],
    ['ninu', ['he']],
    ['ninumahar', ['his']],
    ['nisar', ['close']],
    ['no', ['it']],
    ['nobei', ['showed']],
    ['nomu', ['without']],
    ['noras', ['fellow']],
    ['nudakan', ['order']],
    ['nulis', ['within']],
    ['nut', ['with']],
    ['obana', ['measure', 'measures']],
    ['odora', ['longer']],
    ['oibos', ['fulfill']],
    ['oibosi', ['fulfilled', 'complete']],
    ['ol', ['any']],
    ['olmen', ['everything']],
    ['om', ['all']],
    ['oridion', ['faithfully']],
    ['oro', ['up']],
    ['oromel', ['elevator', 'elevators']],
    ['rahama', ['warrior', 'warriors']],
    ['rem', ['seven']],
    ['sabalba', ['however']],
    ['sabek', ['dangerous']],
    ['sadar', ['scan', 'scans']],
    ['sahali', ['ability']],
    ['sahar', ['aid']],
    ['sahari', ['aided']],
    ['saki', ['even']],
    ['salaku', ['scientist', 'scientists']],
    ['salima', ['destiny', 'destinies']],
    ['samus', ['Samus']],
    ['saral', ['eradicate']],
    ['sarali', ['eradicated']],
    ['sarar', ['gate']],
    ['sarien', ['homeworld']],
    ['sarin', ['stand']],
    ['satar', ['use']],
    ['satari', ['used']],
    ['saveis', ['during']],
    ['sen', ['is']],
    ['shadaha', ['sacrifice', 'sacrifices']],
    ['sharek', ['there']],
    ['sidur', ['go']],
    ['sirugali', ['unforeseen']],
    ['suradis', ['rampant']],
    ['sus', ['most']],
    ['tachela', ['right']],
    ['talar', ['running']],
    ['talaris', ['ran']],
    ['tanumar', ['leader', 'leaders']],
    ['tar', ['of']],
    ['tarin', ['ZDR']],
    ['tebolen', ['extract']],
    ['tera', ['body', 'bodies']],
    ['thoha', ['Thoha']],
    ['tirbon', ['glimpse']],
    ['tostek', ['purpose', 'purposes']],
    ['tsanul', ['end']],
    ['tsegura', ['tolerate']],
    ['tsegurai', ['tolerated']],
    ['tuchoka', ['disobedience']],
    ['tumema', ['resuming']],
    ['turuta', ['worry']],
    ['tutanka', ['disappoint']],
    ['uliris', ['planet', 'planets']],
    ['ulu', ['not', 'no']],
    ['umauka', ['submit']],
    ['umeli', ['awaken']],
    ['umi', ['mind', 'minds']],
    ['ura', ['we', 'us']],
    ['uramahar', ['our']],
    ['uran', ['control']],
    ['uranes', ['satisfactory']],
    ['utanka', ['chaos']],
])